name: Publish Cloudflare base files
on:
  workflow_dispatch: {}
env:
  PUBLISH_REPOSITORY: mogugames/straightpuzzleonline
jobs:
  build:
    name: Run the WebGL build
    runs-on: ubuntu-latest
    steps:
      - name: Check out unity project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Publish to Cloudflare Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: cf-pages
          publish_dir: cloudflare
          external_repository: ${{ env.PUBLISH_REPOSITORY }}
          keep_files: true
